networks:
  favorite-places:

services:
  # GraphQL API Gateway
  favorite-places-gateway:
    build: .
    container_name: favorite-places-gateway
    command: flask --debug run --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./docs:/docs
    env_file:
      - .env
    networks:
      - favorite-places
